training:
  batch_size: 32     # Smaller batch size for quick testing
  learning_rate: 0.001
  num_epochs: 100     # Fewer epochs for quick testing
  enable_early_stopping: false  # Enable/disable early stopping
  early_stopping_patience: 1
  save_every_n_epochs: 25

# Finetuning specific configuration
finetuning:
  foundation_model_path: "./models/foundation_model_final.pth"
  learning_rate: 0.001  # Lower learning rate for finetuning
  num_epochs: 10      # Fewer epochs for finetuning
  enable_early_stopping: true  # Enable/disable early stopping for finetuning
  early_stopping_patience: 5
  save_every_n_epochs: 5
  freeze_backbone: false  # Whether to freeze backbone during finetuning
  
  # Task-specific datasets for finetuning
  tasks:
    # Example classification task
    # - task: "classification"
    #   dataset_name: "pmram"
    #   classes: ["glioma", "meningioma", "normal", "pituitary"]
    #   data_path: "./data/classification/pmram"
    #   model_save_path: "./results/finetuned_pmram/finetuned_pmram.pth"
    #   results_save_path: "./results/finetuned_pmram"

    # Example segmentation task
    - task: "segmentation"
      dataset_name: "brain_stroke"
      num_classes: 2
      data_path: "./data/segmentation/brain_stroke"
      model_save_path: "./ft_results/finetuned_pmram/finetuned_brain_stroke.pth"
      results_save_path: "./ft_results/finetuned_pmram"

model:
  backbone: "efficientnet_b3"
  pretrained: true
  num_classes: null  # Will be set based on dataset
  dropout: 0.2
  use_attention: true  # Enable CBAM and multi-head attention
  num_attention_heads: 8  # Number of attention heads for classification

data:
  image_size: [64, 64]
  max_samples_per_class: null  # Max samples per class for classification (null = all data)
  max_samples_per_dataset: null  # Max samples per dataset for segmentation (null = all data)
  data_fraction: 1.0 # Fraction of data to use for training
  augmentation:
    horizontal_flip: 0.5
    vertical_flip: 0.3
    rotation: 15
    brightness: 0.2
    contrast: 0.2

classification_datasets:
  - name: "brain_mri_nd5"
    classes: ["glioma", "meningioma", "none", "pituitary"]
  - name: "hf_brain_tumor"
    classes: ["glioma", "meningioma", "none", "pituitary"]
  - name: "pancreas"
    classes: ["NPancreas", "PPancreas"]

segmentation_datasets:
  - name: "btcv"
    num_classes: 2  # Binary segmentation
  - name: "cvc_clinicdb"
    num_classes: 2
  - name: "kvasir_seg"
    num_classes: 2
  - name: "medseg_covid"
    num_classes: 2
  - name: "medseg_liver"
    num_classes: 2

paths:
  data_root: "./data"
  models_dir: "./models"
  results_dir: "./results"
  logs_dir: "./logs"

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  suppress_model_loading_warnings: false  # Set to true to suppress expected model loading warnings
